### ISSUE TITLE
Myanmar -UU not shifted right after subjoined KA

### ISSUE THREAD

**Issue by r12a** [notofonts/myanmar#21]
### Font 
  > Latest Noto Sans and Noto Serif fonts.

### Where the font came from, and when
  > https://github.com/googlefonts/noto-fonts/blob/master/hinted/NotoSansMyanmar/NotoSansMyanmar-Regular.ttf Version 2.001; ttfautohint (v1.8.2)
  > https://github.com/googlefonts/noto-fonts/blob/master/hinted/NotoSerifMyanmar/NotoSerifMyanmar-Regular.ttf
  >   Date: 2020-09-14 (preferred format) Version 2.001;GOOG;noto-source:20171016:bf6466d78425

### OS name and version
Mac OS Mojave 10.14.6

### Application name and version
Firefox, Chrome

### Issue
Noto fonts produce overlap.

![Screenshot 2020-09-14 at 11 27 17](https://user-images.githubusercontent.com/4839211/93075178-5542af80-f67d-11ea-9cd0-ccc685baec62.png)

  > Expected result (paduak book)

![Screenshot 2020-09-14 at 11 28 59](https://user-images.githubusercontent.com/4839211/93075311-84592100-f67d-11ea-8757-392ed6f7e463.png)

### Character data

စက္ကူ

စ U+1005 MYANMAR LETTER CA
က U+1000 MYANMAR LETTER KA
္ U+1039 MYANMAR SIGN VIRAMA
က U+1000 MYANMAR LETTER KA
ူ U+1030 MYANMAR VOWEL SIGN UU

## Tools for reporting bugs
http://r12a.github.io/pickers/burmese/?text=%E1%80%85%E1%80%80%E1%80%B9%E1%80%80%E1%80%B0

**Comment by simoncozens** [comment]
Yes, this is now fixed; subjoined ka makes the uu go postbase:
![shape](https://user-images.githubusercontent.com/106728/215127327-45e38870-f3a8-44a2-8a88-bee895b7b51c.png)
