### ISSUE TITLE
ၣ် 1063 & 103A Noto Sans Myanmar issue still not resolved

### ISSUE THREAD

**Issue by taylorcanning** [notofonts/myanmar#25]
ၣ် 1063 & 103A Noto Sans Myanmar issue still not resolved, the combination does not render correctly. this is a very common S'Gaw Karen tone that is used very often. please see attached document.
[noto sans error.docx](https://github.com/googlei18n/noto-fonts/files/426088/noto.sans.error.docx)

**Comment by simoncozens** [comment]
There isn't a font issue here; the hathi combines with the asat in Harfbuzz. If there's still an issue, it's with Microsoft's syllable definitions, but I believe they have been fixed too.
