### ISSUE TITLE
Add language-specific letterforms for Khamti Shan, Aiton, and Phake

### ISSUE THREAD

**Issue by brawer** [notofonts/myanmar#27]
In Noto Myanmar, would it be possible to implement `locl` features for the Khamti Shan, Aiton, and Phake languages? See Unicode notes [L2015/15-257](http://unicode.org/L2/L2015/15257-khamti-disunify.pdf) and [L2015/15-320](http://unicode.org/L2/L2015/15320-khamti-vs.pdf) for background and images.

The Noto font already contains the needed glyphs with “dotted” shapes. Currently, users get them via Unicode Variation Selectors — this is correct, and should be preserved. However, in addition to Variation Selectors, it would be nice if the font also used the dotted glyph shapes when the text was language-tagged with OpenType language system tags `KHT` Khamti Shan, Aiton `AIO`, or Phake `PHK`. Hence the request to add an OpenType `locl` feature to the GSUB table.

cc @mhosken who wrote Unicode notes [L2015/15-257](http://unicode.org/L2/L2015/15257-khamti-disunify.pdf) and [L2015/15-320](http://unicode.org/L2/L2015/15320-khamti-vs.pdf), and @sven-oly who is also interested in this.

**Comment by simoncozens** [comment]
This is a duplicate of #26. To the general point, we're aware that there are many issues with the Myanmar fonts and we have plans (well, dreams, really) to re-engineer the font; this will include better support for minority languages using the Myanmar script, but it won't happen in the next year.
