### ISSUE TITLE
Winding errors in Noto Serif Myanmar

### ISSUE THREAD

**Issue by dscorbett** [notofonts/myanmar#7]
### Font
NotoSerifMyanmar-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/34e98229863e627d0f841e124a8657d5d0348b04/phaseIII_only/unhinted/ttf/NotoSerifMyanmar/NotoSerifMyanmar-Regular.ttf
Date: 2019-06-09

### Font version
Version 2.001

### Issue
Some Myanmar glyphs are rasterized wrong: they have mirrored references that overlap non-mirrored references.

### Character data
ရှႁႂꩠꩾꩾွꩿွ
U+101B MYANMAR LETTER RA
U+103E MYANMAR CONSONANT SIGN MEDIAL HA
U+1081 MYANMAR LETTER SHAN HA
U+1082 MYANMAR CONSONANT SIGN SHAN MEDIAL WA
U+AA60 MYANMAR LETTER KHAMTI GA
U+AA7E MYANMAR LETTER SHWE PALAUNG CHA
U+AA7E MYANMAR LETTER SHWE PALAUNG CHA
U+103D MYANMAR CONSONANT SIGN MEDIAL WA
U+AA7F MYANMAR LETTER SHWE PALAUNG SHA
U+103D MYANMAR CONSONANT SIGN MEDIAL WA

### Screenshot
![ရှႁႂꩠꩾꩾွꩿွ](https://user-images.githubusercontent.com/1124347/59204603-fb486580-8b6e-11e9-973a-dd090f1a53f1.png)

**Comment by pyiso80** [comment]
Any possibility to get this problem fixed in the near future?

**Comment by simoncozens** [comment]
We now do decompose transformed components during building, so this should be fixed. Please try the fonts at https://notofonts.github.io/myanmar/

**Comment by pyiso80** [comment]
Thanks a lot! Already fixed!!!

![CleanShot 2022-08-13 at 21 42 58@2x](https://user-images.githubusercontent.com/177145/184500172-1fcfcc28-0b22-4c2d-b2b6-fdcc8f4e2db5.jpg)

Full version didn't give me the correct result. I tried unhinted version and the rendering is correct as shown above. What's the difference between hinted and unhinted? By the way, I am using XeLaTex to render the fonts.

Full version gave me like this:
![CleanShot 2022-08-13 at 21 46 39@2x](https://user-images.githubusercontent.com/177145/184500354-99bd38d9-28a2-4601-881b-98f7fc672208.jpg)

I wish I could use english letters as well while I am using Noto Myanmar font. Unhinted and hinted version don't have glyphs for latin alphabets. :(. I need to find some workarounds to replace with other font when not available.

For instance,  to get " Section ၁.၂.၁" (equivalent to. 1.2.1 in English), I need to take period from other fonts and substitute at the right place. Fortunately, Latex can do it well just by using a few fontky tricks.

**Comment by simoncozens** [comment]
"Full" and "Googlefonts" versions will have Latin core glyphs added. The winding looks fine in the "googlefonts" version for me:
![shape](https://user-images.githubusercontent.com/106728/184503834-1d7f5f71-3114-4d5b-88f5-b5f8294abfff.png)

The shaping is of course a mess but that's another problem...
